INSERT INTO tb_category(name, created_At) VALUES('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Health', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Beauty', NOW());
INSERT INTO tb_category(name, created_At) VALUES('House and Decoration', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Home Appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Clothes', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Acessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Automobiles', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Mobile Devices', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Hobbies', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Bags', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Sport', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Leisure', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Kids Fashion', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Kids', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Pet Shop', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Musical Equipment', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Tools', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Drones', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Courses', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Printers', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Scanners', NOW());
INSERT INTO tb_category(name, created_At) VALUES('School Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Hunting', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Fishing', NOW());